### ISSUE TITLE
Set encoding when opening file

### ISSUE THREAD

**Issue by daniel-pebble** [ThioJoe/SRT-To-SSML#2]
Hit the following while testing with a danish SRT file. 
![image](https://user-images.githubusercontent.com/47243318/208184827-1fb1a390-ff70-43b7-8a3d-0b683e11d310.png)

Setting the opening encoding mode to utf-8-sig fixed the issue for me
```
with open(srtFile, 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()
```

**Comment by ThioJoe** [comment]
This _could_ be dependent on the program that created the srt file. I think I'll add a check so that it will open the file with the right encoding.
