### ISSUE TITLE
Can't Recreate Example

### ISSUE THREAD

**Issue by mrashco** [ThioJoe/SRT-To-SSML#4]
So I'm trying to get SRT to SSML working for another TTS service (https://blakify.com/).

I (mostly) have SRT-To-SSML working with my own SRT file... yet as a baseline, I can't get the example SRT from README.md to even work. See the example below.

*note, I've modified the script to use sys.argv as arguments
![image](https://user-images.githubusercontent.com/22973982/222121207-f631f1f3-7d3b-447a-b072-afe9be88e218.png)

I also noticed in both my own SRT file and by commenting out lines 102-109... that the SSML generated won't include <break time="***"/> elements.

I'd appreciate any guidance or help, thanks!

**Comment by ThioJoe** [comment]
Ok it happens when I tried it too, I'll have to see what the issue is

**Comment by ThioJoe** [comment]
Ok just released a new commit https://github.com/ThioJoe/SRT-To-SSML/commit/31454e66165f1283aabc464c125b94221c9dd485 

So try the latest version of the file, should work.

**Comment by mrashco** [comment]
Thanks! 

And the "break" elements were showing up when generating the SSML. I'll give it another crack.
